name: fd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  permission_handler: ^12.0.1
  face_verification: ^0.3.8
  google_mlkit_face_detection: 0.14.0
  geolocator: ^13.0.2
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg